services:
  redis:
    image: redis:7-alpine
    container_name: ghly-redis
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  ghly:
    image: ghly:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghly
    ports:
      - "${SERVER_PORT-8000}:${SERVER_PORT-8000}"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: python app/main.py
    depends_on:
      - redis
  

volumes:
  redis-data:
    driver: local
